name: Semantic Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        concurrency: release
        permissions:
            id-token: write
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - name: Python Semantic Release
              id: release
              uses: python-semantic-release/python-semantic-release@v9.21.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: steps.release.outputs.released == 'true'
